package com.morpheusdata.core.synchronous.network.loadbalancer;

import com.morpheusdata.core.MorpheusSynchronousIdentityService;
import com.morpheusdata.core.MorpheusSynchronousDataService;
import com.morpheusdata.model.NetworkLoadBalancerNode;
import com.morpheusdata.model.projection.LoadBalancerNodeIdentityProjection;

public interface MorpheusSynchronousLoadBalancerNodeService extends MorpheusSynchronousDataService<NetworkLoadBalancerNode, LoadBalancerNodeIdentityProjection>, MorpheusSynchronousIdentityService<LoadBalancerNodeIdentityProjection> {
}
