/*
 *  Copyright 2024 Morpheus Data, LLC.
 *
 * Licensed under the PLUGIN CORE SOURCE LICENSE (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://raw.githubusercontent.com/gomorpheus/morpheus-plugin-core/v1.0.x/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.morpheusdata.core.network.loadbalancer;

import com.morpheusdata.core.MorpheusDataService;
import com.morpheusdata.core.MorpheusIdentityService;
import com.morpheusdata.model.NetworkLoadBalancer;
import com.morpheusdata.model.NetworkLoadBalancerProfile;
import com.morpheusdata.model.projection.LoadBalancerProfileIdentityProjection;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface MorpheusLoadBalancerProfileService extends MorpheusDataService<NetworkLoadBalancerProfile, LoadBalancerProfileIdentityProjection>, MorpheusIdentityService<LoadBalancerProfileIdentityProjection> {
	/**
	 * Get a list of {@link NetworkLoadBalancerProfile} projections based on NetworkLoadBalancer id
	 *
	 * @param loadBalancerId the id of the load balancer
	 * @return Observable stream of sync projection
	 */
	Observable<LoadBalancerProfileIdentityProjection> listSyncProjections(Long loadBalancerId);

	/**
	 * Get a list of {@link NetworkLoadBalancerProfile} objects from a list of projection ids
	 *
	 * @param ids ids of load balancer nodes
	 * @return Observable stream of {@link NetworkLoadBalancerProfile} objects
	 */
	@Deprecated(since="0.15.4")
	Observable<NetworkLoadBalancerProfile> listById(Collection<Long> ids);

	/**
	 * Save updates to existing profiles
	 *
	 * @param profiles updated {@link NetworkLoadBalancerProfile} objects
	 * @return success
	 * @deprecated use {@link #bulkSave } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> save(List<NetworkLoadBalancerProfile> profiles);

	/**
	 * Create new profiles in Morpheus
	 *
	 * @param profiles new {@link NetworkLoadBalancerProfile} objects to persist
	 * @return success
	 * @deprecated use {@link #bulkCreate } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> create(List<NetworkLoadBalancerProfile> profiles);

	/**
	 * Remove persisted profiles from Morpheus
	 *
	 * @param profiles {@link LoadBalancerProfileIdentityProjection} objects to delete from database
	 * @return success
	 * @deprecated use {@link #bulkRemove } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> remove(List<LoadBalancerProfileIdentityProjection> profiles);

	/**
	 * retrieve a load balancer profile by external id and load balancer (used in syncing)
	 * @param externalId the id of the {@link NetworkLoadBalancerProfile} generated by the integration
	 * @param loadBalancer {@link NetworkLoadBalancer}
	 * @return 1 or 0 {@link NetworkLoadBalancerProfile}
	 */
	@Deprecated(since="0.15.4")
	Single<Optional<NetworkLoadBalancerProfile>> findByExternalIdAndLoadBalancer(String externalId, NetworkLoadBalancer loadBalancer);

	/**
	 * Use this method to query the database for load balancer profiles
	 * @param args a map of properties used to query the profiles
	 * @return Observable stream of {@link NetworkLoadBalancerProfile}
	 */
	@Deprecated(since="0.15.4")
	Observable<NetworkLoadBalancerProfile> queryProfiles(Map args);
}
