package com.morpheusdata.core.network.loadbalancer;

import com.morpheusdata.core.MorpheusDataService;
import com.morpheusdata.core.MorpheusIdentityService;
import com.morpheusdata.model.NetworkLoadBalancerMonitor;
import com.morpheusdata.model.projection.LoadBalancerMonitorIdentityProjection;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Interface for interacting with the morpheus backend database in regards to load balancer health monitor domain objects
 */
public interface MorpheusLoadBalancerMonitorService extends MorpheusDataService<NetworkLoadBalancerMonitor, LoadBalancerMonitorIdentityProjection>, MorpheusIdentityService<LoadBalancerMonitorIdentityProjection> {
	/**
	 * Get a list of {@link NetworkLoadBalancerMonitor} projections based on NetworkLoadBalancer id
	 *
	 * @param loadBalancerId the id of the load balancer
	 * @return Observable stream of sync projection
	 */
	Observable<LoadBalancerMonitorIdentityProjection> listSyncProjections(Long loadBalancerId);

	/**
	 * Get a list of NetworkLoadBalancerNode objects from a list of projection ids
	 *
	 * @param ids ids of load balancer monitors
	 * @return Observable stream of NetworkLoadBalancerMonitor objects
	 */
	@Deprecated(since="0.15.4")
	Observable<NetworkLoadBalancerMonitor> listById(Collection<Long> ids);

	/**
	 * Save updates to existing monitor
	 *
	 * @param monitors updated {@link NetworkLoadBalancerMonitor} objects
	 * @return success
	 * @deprecated use {@link #bulkSave } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> save(List<NetworkLoadBalancerMonitor> monitors);

	/**
	 * Create new monitor in Morpheus
	 *
	 * @param monitors new {@link NetworkLoadBalancerMonitor} objects to persist
	 * @return success
	 * @deprecated use {@link #bulkCreate } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> create(List<NetworkLoadBalancerMonitor> monitors);

	/**
	 * Remove persisted monitor from Morpheus
	 *
	 * @param monitors {@link LoadBalancerMonitorIdentityProjection} objects to delete from database
	 * @return success
	 * @deprecated use {@link #bulkRemove } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> remove(List<LoadBalancerMonitorIdentityProjection> monitors);

	/**
	 * Helper method to look up a network load balancer health monitor by its externalId (The id on the api side)
	 * @param externalId the identifier of the load balancer monitor generated by the integration
	 * @return 0 o 1 NetworkLoadBalancerMonitors
	 */
	Single<Optional<NetworkLoadBalancerMonitor>> findByExternalId(String externalId);

	/**
	 * Helper method to look up a network load balancer health monitor by its id
	 * @param id of the monitor to retrieve
	 * @return 0 o 1 NetworkLoadBalancerMonitors
	 */
	Single<Optional<NetworkLoadBalancerMonitor>> findById(Long id);

	/**
	 * Use this method to query the database for load balancer health monitors
	 * @param args a map of properties used to query the health monitors
	 * @return Observable stream of {@link NetworkLoadBalancerMonitor}
	 */
	Observable<NetworkLoadBalancerMonitor> queryHealthMonitors(Map args);
}
