/*
 *  Copyright 2024 Morpheus Data, LLC.
 *
 * Licensed under the PLUGIN CORE SOURCE LICENSE (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://raw.githubusercontent.com/gomorpheus/morpheus-plugin-core/v1.0.x/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.morpheusdata.core.network.loadbalancer;

import com.morpheusdata.core.MorpheusDataService;
import com.morpheusdata.core.MorpheusIdentityService;
import com.morpheusdata.model.NetworkLoadBalancer;
import com.morpheusdata.model.NetworkLoadBalancerPolicy;
import com.morpheusdata.model.projection.LoadBalancerPolicyIdentityProjection;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface MorpheusLoadBalancerPolicyService extends MorpheusDataService<NetworkLoadBalancerPolicy, LoadBalancerPolicyIdentityProjection>, MorpheusIdentityService<LoadBalancerPolicyIdentityProjection> {
	/**
	 * Get a list of {@link LoadBalancerPolicyIdentityProjection} projections based on NetworkLoadBalancer id
	 *
	 * @param loadBalancerId the id of the load balancer
	 * @param objCategory a category name used in sync comparison
	 * @return Observable stream of sync projection
	 */
	Observable<LoadBalancerPolicyIdentityProjection> listSyncProjections(Long loadBalancerId, String objCategory);

	/**
	 * Get a list of {@link NetworkLoadBalancerPolicy} objects from a list of projection ids
	 *
	 * @param ids list of policy ids
	 * @return Observable stream of policies
	 */
	@Deprecated(since="0.15.4")
	Observable<NetworkLoadBalancerPolicy> listById(Collection<Long> ids);

	/**
	 * Save updates to existing policy
	 *
	 * @param policies updated policy
	 * @return success
	 * @deprecated use {@link #bulkSave } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> save(List<NetworkLoadBalancerPolicy> policies);

	/**
	 * Create new policies in Morpheus
	 *
	 * @param policies new NetworkLoadBalancerPolicy to persist
	 * @return success
	 * @deprecated use {@link #bulkCreate } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> create(List<NetworkLoadBalancerPolicy> policies);

	/**
	 * Remove persisted policies from Morpheus
	 *
	 * @param policies Images to delete
	 * @return success
	 * @deprecated use {@link #bulkRemove } instead
	 */
	@Deprecated(since="0.15.4")
	Single<Boolean> remove(List<LoadBalancerPolicyIdentityProjection> policies);

	/**
	 * Retrive a load balancer policy based on externalId and load balancer (used in sync)
	 * @param externalId the id of the load balancer policy generated by the integration
	 * @param loadBalancer {@link NetworkLoadBalancer}
	 * @return a {@link NetworkLoadBalancerPolicy} if found in the morpheus db
	 */
	Single<Optional<NetworkLoadBalancerPolicy>> findByExternalIdAndLoadBalancer(String externalId, NetworkLoadBalancer loadBalancer);

	/**
	 * This method will retrieve a load balancer policy based on its morpheus primary key
	 * @param id - morpheus primary key for policy
	 * @return a {@link NetworkLoadBalancerPolicy} if found in the morpheus db
	 */
	@Deprecated(since="0.15.4")
	Single<Optional<NetworkLoadBalancerPolicy>> findById(Long id);

	/**
	 * Use this method to query the database for load balancer policies
	 * @param args a map of properties used to query the policy
	 * @return Observable stream of {@link NetworkLoadBalancerPolicy}
	 */
	@Deprecated(since="0.15.4")
	Observable<NetworkLoadBalancerPolicy> queryPolicies(Map args);
}
