package com.morpheusdata.core.network.loadbalancer;

import com.morpheusdata.model.NetworkLoadBalancer;
import com.morpheusdata.model.NetworkLoadBalancerPolicy;
import com.morpheusdata.model.projection.LoadBalancerPolicyIdentityProjection;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface MorpheusLoadBalancerPolicyService {
	/**
	 * Get a list of {@link LoadBalancerPolicyIdentityProjection} projections based on NetworkLoadBalancer id
	 *
	 * @param loadBalancerId the id of the load balancer
	 * @param objCategory a category name used in sync comparison
	 * @return Observable stream of sync projection
	 */
	Observable<LoadBalancerPolicyIdentityProjection> listSyncProjections(Long loadBalancerId, String objCategory);

	/**
	 * Get a list of {@link NetworkLoadBalancerPolicy} objects from a list of projection ids
	 *
	 * @param ids list of policy ids
	 * @return Observable stream of policies
	 */
	Observable<NetworkLoadBalancerPolicy> listById(Collection<Long> ids);

	/**
	 * Save updates to existing policy
	 *
	 * @param policies updated policy
	 * @return success
	 */
	Single<Boolean> save(List<NetworkLoadBalancerPolicy> policies);

	/**
	 * Create new policies in Morpheus
	 *
	 * @param policies new NetworkLoadBalancerPolicy to persist
	 * @return success
	 */
	Single<Boolean> create(List<NetworkLoadBalancerPolicy> policies);

	/**
	 * Remove persisted policies from Morpheus
	 *
	 * @param policies Images to delete
	 * @return success
	 */
	Single<Boolean> remove(List<LoadBalancerPolicyIdentityProjection> policies);

	/**
	 * Retrive a load balancer policy based on externalId and load balancer (used in sync)
	 * @param externalId the id of the load balancer policy generated by the integration
	 * @param loadBalancer {@link NetworkLoadBalancer}
	 * @return a {@link NetworkLoadBalancerPolicy} if found in the morpheus db
	 */
	Single<Optional<NetworkLoadBalancerPolicy>> findByExternalIdAndLoadBalancer(String externalId, NetworkLoadBalancer loadBalancer);

	/**
	 * This method will retrieve a load balancer policy based on its morpheus primary key
	 * @param id - morpheus primary key for policy
	 * @return a {@link NetworkLoadBalancerPolicy} if found in the morpheus db
	 */
	Single<Optional<NetworkLoadBalancerPolicy>> findById(Long id);

	/**
	 * Use this method to query the database for load balancer policies
	 * @param args a map of properties used to query the policy
	 * @return Observable stream of {@link NetworkLoadBalancerPolicy}
	 */
	Observable<NetworkLoadBalancerPolicy> queryPolicies(Map args);
}
