package com.morpheusdata.core.network.loadbalancer;

import com.morpheusdata.model.NetworkLoadBalancer;
import com.morpheusdata.model.NetworkLoadBalancerMember;
import com.morpheusdata.model.NetworkLoadBalancerPool;
import com.morpheusdata.model.projection.LoadBalancerPoolIdentityProjection;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface MorpheusLoadBalancerPoolService {
	/**
	 * Get a list of {@link NetworkLoadBalancerPool} projections based on NetworkLoadBalancer id
	 *
	 * @param loadBalancerId the id of the load balancer
	 * @return Observable stream of sync projection
	 */
	Observable<LoadBalancerPoolIdentityProjection> listSyncProjections(Long loadBalancerId);

	/**
	 * Get a list of {@link NetworkLoadBalancerPool} objects from a list of projection ids
	 *
	 * @param ids pool ids
	 * @return Observable stream of pools
	 */
	Observable<NetworkLoadBalancerPool> listById(Collection<Long> ids);

	/**
	 * Save updates to existing pool
	 *
	 * @param pools updated pools
	 * @return success
	 */
	Single<Boolean> save(List<NetworkLoadBalancerPool> pools);

	/**
	 * Create new load balancer pool in Morpheus
	 *
	 * @param pools new {@link NetworkLoadBalancerPool}  to persist
	 * @return success
	 */
	Single<Boolean> create(List<NetworkLoadBalancerPool> pools);

	/**
	 * Remove persisted load balancer pools from Morpheus
	 *
	 * @param pools Images to delete
	 * @return success
	 */
	Single<Boolean> remove(List<LoadBalancerPoolIdentityProjection> pools);

	/**
	 * Retrieves a single load balancer pool from the database given a load balancer and external id
	 * @param loadBalancer {@link NetworkLoadBalancer}
	 * @param externalId the id of the {@link NetworkLoadBalancerPool} generated by the integration
	 * @return 1 or 0 {@link NetworkLoadBalancerPool}
	 */
	Single<Optional<NetworkLoadBalancerPool>> findByLoadBalancerAndExternalId(NetworkLoadBalancer loadBalancer, String externalId);

	/**
	 * This method is used to grab the persisted pool members for a given load balancer pool
	 * @param pool {@link NetworkLoadBalancerPool}
	 * @return an observable stream of {@link NetworkLoadBalancerMember}
	 */
	Observable<NetworkLoadBalancerMember> getPoolMembers(NetworkLoadBalancerPool pool);
}
