package com.morpheusdata.test

import com.morpheusdata.core.MorpheusOperationNotificationService
import groovy.transform.AutoImplement

@AutoImplement
class MorpheusOperationNotificationServiceImpl implements MorpheusOperationNotificationService {
}
