package com.morpheusdata.core.synchronous;

import com.morpheusdata.core.MorpheusSynchronousIdentityService;
import com.morpheusdata.core.MorpheusSynchronousDataService;
import com.morpheusdata.model.StorageServer;
import com.morpheusdata.model.projection.StorageServerIdentityProjection;

public interface MorpheusSynchronousStorageServerService extends MorpheusSynchronousDataService<StorageServer, StorageServerIdentityProjection>, MorpheusSynchronousIdentityService<StorageServerIdentityProjection> {
}
