package com.morpheusdata.core.synchronous;

import com.morpheusdata.core.MorpheusSynchronousIdentityService;
import com.morpheusdata.core.MorpheusSynchronousDataService;
import com.morpheusdata.model.SecurityGroupRuleProfile;

public interface MorpheusSynchronousSecurityGroupRuleProfileService extends MorpheusSynchronousDataService<SecurityGroupRuleProfile, SecurityGroupRuleProfile> {
}
