package com.morpheusdata.core.synchronous;

import com.morpheusdata.core.MorpheusSynchronousIdentityService;
import com.morpheusdata.core.MorpheusSynchronousDataService;
import com.morpheusdata.model.AccountPriceSet;
import com.morpheusdata.model.projection.AccountPriceSetIdentityProjection;

public interface MorpheusSynchronousAccountPriceSetService extends MorpheusSynchronousDataService<AccountPriceSet, AccountPriceSetIdentityProjection>, MorpheusSynchronousIdentityService<AccountPriceSetIdentityProjection> {
}
