package com.morpheusdata.core.synchronous;

import com.morpheusdata.core.MorpheusSynchronousIdentityService;
import com.morpheusdata.core.MorpheusSynchronousDataService;
import com.morpheusdata.model.SecurityGroupRuleDestination;

public interface MorpheusSynchronousSecurityGroupRuleDestinationService extends MorpheusSynchronousDataService<SecurityGroupRuleDestination, SecurityGroupRuleDestination> {
}
