name: Plugin API CI
on:
  push:
    branches-ignore:
      - 'master'
    paths:
      - 'morpheus-plugin-api/**'
      - '.github/workflows/build-plugin-api.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Setup JDK 17
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: test
      run: ./gradlew morpheus-plugin-api:test --no-daemon
    - name: javadoc
      run: ./gradlew morpheus-plugin-api:javadoc --no-daemon
    - name: assemble
      run: ./gradlew morpheus-plugin-api:assemble --no-daemon
    - uses: actions/upload-artifact@v2
      with:
          name: plugin-artifacts
          path: plugins/

