=== Cloud Provider Plugins

The Cloud provider plugin interfaces are among the more complicated plugin types to implement within Morpheus, but when implemented successfully it provides a very powerful method for creating custom clouds or even updating existing cloud functionality. There are two primary concepts that must first be discussed when developing a cloud plugin.

A Cloud plugin typically defines a cloud type (you may see this as `zoneType` in api for legacy compatibility.) as well as at least one `ProvisionProvider`. A Provision Provider (also seen in api as `provisionType`) defines how a resource is provisioned within a cloud. A cloud could offer many provisioning types. For example, Amazon offers both `EC2` as well as `RDS`.

There are several other provider implementations that are needed on more advanced cloud implementations and some are not yet built out. This includes `NetworkProvider` and `BackupProvider` implementations as well as a few more.

==== Setup

Before Getting Started, It is recommended to look at the digital ocean sample plugin just to get some bearings. To get started you firstly will create a new class that implements `com.morpheusdata.core.CloudProvider`. The `CloudProvider` requires implementation of several methods including the code required to sync existing workloads from the cloud. All sync related code normally lives in here. 

On a cloud implementation there are 2 scheduled jobs for refreshing. There is firstly a 5 minute sync job (typically) that syncs state changes on a periodic basis. Then secondly a daily job that runs at Midnight UTC to do larger syncs like price data or things that may change less frequently. Refer to implementations of the `refresh()` method as well as the `refreshDaily()` methods.

Finally one must also provide the option types inputs for configuring the add cloud wizard as well as the `ComputeServerType` objects available to this zone type. There should be multiple based often on platform and management state.

==== Defining Credentials

During the `refresh()` call (and others) the `CloudProvider` implementation will need to reach out to underlying cloud using credentials. There are two ways to define and store the required credentials.

===== Using OptionTypes
The simplest method is to define `OptionType` fields (like username and password) and return them on implementation of `CloudProvider.getOptionTypes()`. These will then be displayed on the Cloud configuration UI. The values can then be obtained during sync operations via the Cloud's `getConfigMap` or directly on the object itself (i.e. `serviceUsername`) depending on how the `OptionType` was defined.

===== Using Morpheus Credentials
A more flexible option is to use Morpheus' built-in Credentials support. With this option, Credentials can be stored securely in Morpheus and utilized in various locations. In order to user this method, a few specific `OptionType` objects need to be defined. (Refer to `VmwareCloudProvider` for an example implementation)

. An `OptionType` needs to be defined to represent the selection of the Credential type. The following properties must be configured on the `OptionType`: `inputType=OptionType.InputType.CREDENTIAL`, `fieldContext=credential`, `fieldName=type`, `optionSource=credentials`. In addition, the `config` for the `OptionType` should be something like `'{"credentialTypes":["username-password"]}'`. Where the array of types may be one or more of `username-password,
username-password-keypair,
username-keypair,
access-key-secret,
client-id-secret,
username-api-key,
email-private-key,
tenant-username-keypair,
oauth2,
api-key`. These represent the preconfigured credential types in Morpheus.
. `OptionType` objects need to be defined to represent the 'local' auth values. For example, username and password would need their own `OptionType`. For these 'local' types, their `localCredential` value must be `true`
. Any `OptionTypes` that should be reloaded when the Credential input changes should include `credential-type` in their `dependsOn` value. This will trigger the `OptionType` `optionSource` function to be called when the Credentials change.

To load the Credential information that may be set on a Cloud, the `MorpheusCloudService` can be used.

To load the Credential information from within `OptionSourceService` implementations (which may be called during Cloud configuration), `MorpheusAccountCredentialService` may be used to load Credential information from the passed in form options. See `VmwareOptionSourceService` for an example.
