== Credential Provider Inputs

During the 5.4.x and 5.5.x release of Morpheus. Credentials were introduced. It became possible to store integration credentials externally or decoupled from a specific integration. This is great for service accounts! As a result a new option type was created to allow them to be used for custom plugin integrations.

=== Getting Started

Most of the time, this setup will be used when defining available OptionTypes in the various Provider types that have them. For example, an `IPAMProvider` as a method for `getIntegrationOptionTypes()`. The idea is to also support local credential inputs like the simple `serviceUsername` and `servicePassword` fields.  To do this simply add the flag `localCredential:true` to those fields so the system knows, when using local credentials, to show those fields. An example of a credential provider being used can be seen here.


[source,groovy]
----
class InfobloxProvider implements IPAMProvider, DNSProvider {
@Override
    List<OptionType> getIntegrationOptionTypes() {
        return [
                new OptionType(code: 'infoblox.serviceUrl', name: 'Service URL', inputType: OptionType.InputType.TEXT, fieldName: 'serviceUrl', fieldLabel: 'API Url', fieldContext: 'domain', placeHolder: 'https://x.x.x.x/wapi/v2.2.1', helpBlock: 'Warning! Using HTTP URLS are insecure and not recommended.', displayOrder: 0, required:true),
                new OptionType(code: 'infoblox.credentials', name: 'Credentials', inputType: OptionType.InputType.CREDENTIAL, fieldName: 'type', fieldLabel: 'Credentials', fieldContext: 'credential', required: true, displayOrder: 1, defaultValue: 'local',optionSource: 'credentials',config: '{"credentialTypes":["username-password"]}'),

                new OptionType(code: 'infoblox.serviceUsername', name: 'Service Username', inputType: OptionType.InputType.TEXT, fieldName: 'serviceUsername', fieldLabel: 'Username', fieldContext: 'domain', displayOrder: 2,localCredential: true),
                new OptionType(code: 'infoblox.servicePassword', name: 'Service Password', inputType: OptionType.InputType.PASSWORD, fieldName: 'servicePassword', fieldLabel: 'Password', fieldContext: 'domain', displayOrder: 3,localCredential: true),

                ...
}
----

Note the `infoblox.credentials` option type and its use of the type `OptionType.InputType.CREDENTIAL`. The `optionSource` is critical as well as the list of possible credential types seen in the `config` block. 

There are other credential types available that will be populated in this documentation later.


=== Using Credentials in your plugin.

When making remote calls to the integration code it is important to reference the credential data correctly. For example, it is no longer simply a matter of referencing `poolServer.serviceUsername` or `poolServer.servicePassword`. Instead it is important to check the `credentialData` map on the `AccountIntegration`, `Cloud`, or `NetworkPoolServer`.

[source,groovy]
----
    results = client.callApi(serviceUrl, apiPath, poolServer.credentialData?.username ?: poolServer.serviceUsername, poolServer.credentialData?.password ?: poolServer.servicePassword, new HttpApiClient.RequestOptions(headers:['Content-Type':'application/json'], ignoreSSL: poolServer.ignoreSsl,body:body), 'POST')
----

An example can be seen above where the credentialData is first checked.

