== DataSet Providers

A DataSetProvider is a server side call to load a dynamic data for custom form inputs, as well as data references with scribe templates. A dataset can feed data to dropdown lists, multiselect components, and typeahead components. Datasets can be very useful when designing task types that have custom options or even custom catalog item layouts. In the past, this type of data was provided with an `OptionSourceProvider` which contained multiple definitions in a single provider, but had its own limitations and did not provide sufficient documentation on the data provided. The `DataSetProvider` improved dynamic data definitions by: isolating one dataset per provider, including associative information so that it can be used for export/import scribe functionality,  and including documentation on the dataset within the dataset definition.

=== Getting Started

Create an implementation of a `DataSetProvider` or with some convenience methods an `AbstractDataSetProvider`.

When defining an `OptionType` set the `optionSource` property to the `getKey()` defined in the dataset provider. Avoid naming conflicts with other plugins with unique method name or isolate the dataset by using a namespaces. A namespace is set on the `namespace` property of the `DatasetInfo` in `getDataset()`. Alternatively, the `getNamespace()` method can be implemented or overridden. When a dataset is namespaced the  `optionSourceType` of an `OptionType` or `OptionSource` should correlate to the dataset's namespace.

[TIP]
Use a unique namespace for your DataSetProvider to isolate from other plugins.

[source,groovy]
----
OptionType ot4 = new OptionType(
name: 'Region',
code: 'google-plugin-region',
fieldName: 'googleRegionId',
optionSourceType: 'google', // Note: this references the dataset namespace.
optionSource: 'googlePluginRegions', // Note: this references the dataset key.
displayOrder: 3,
fieldLabel: 'Region',
required: true,
inputType: OptionType.InputType.SELECT,
dependsOn: 'google-plugin-project-id',
fieldContext: 'config'
)
----

DatasetProvider examples can be found in the https://github.com/gomorpheus/morpheus-plugin-dataset-examples/tree/main/src/main/groovy/com/morpheusdata/datasets[example plugin repository,role=external,window=_blank] on GitHub.

