== Getting Started

Developing plugins for Morpheus is a bit different than simply creating custom tasks or custom library items in Morpheus. It requires some programming experience. We should preface with the fact that Morpheus runs on top of Java. It is primarily written in a dynamic language called https://groovy-lang.org[Groovy] and is based on Groovy version 2.5 currently running within Java 8 (openjdk). The provided plugin api dependency provides a common set of interfaces a developer can implement to dynamically load functionality into the product. These developers are free to develop plugins in native Java or leverage the groovy runtime. Most examples provided are developed and sampled in groovy. It is a great dynamic language that is much less verbose and easier to understand than native java based languages. Plans for supporting additional languages are in the works. Most notably kotlin is being looked into as an alternative development platform. jRuby is also a viable language that can be used as the runtime is included with Morpheus. The plugin architecture is designed based on reactive models using `rxJava2`. This library follows http://reactivex.io/[ReactiveX] models for Observer pattern based programming. One unique thing about Observer pattern programming is to remember when writing a call to an `Observable` the code is not executed until the final `subscribe` call. If this call is missing, the code will never execute.

**NOTE:** `rxJava3` is a different project build and cannot be used yet in place of `rxJava2`.

The plugin pipeline leverages https://gradle.org[Gradle] as the build tooling. Gradle is a cross-platform programmatic build tool that is very commonly used and is most notably also used in the android space. To begin make sure your development environment has Gradle 6.5 (at least) as well as Java 8 or Java 11 (if using openjdk11 make sure target compatibility is set to 1.8 within your project).

**NOTE:** Groovy 2.5.x does not run/compile correctly in the latest java versions. This will change as we move to Groovy 3 in the near term future.

The https://github.com/gomorpheus/morpheus-plugin-core[morpheus-plugin-core] git repository is structured such that sample plugins exist underneath the `samples` directory. They are part of a multi-project gradle project as can be defined in the root directories `settings.gradle`. This adds a bit of complexity and should be ignored when developing ones own plugin. Simply start with a blank project folder and a simple `build.gradle` as demonstrated below.

The structure of a Plugin is a typical "fat jar" (aka shadowJar). The plugin will include `morpheus-plugin-api` along with all the dependencies required to run. Though not required, it is often conventional to use the groovy programming language when developing plugins as can be seen in the samples. Morpheus is based on the groovy runtime and therefore allows full use of groovy 2.5.x.

The Structure of a project often starts with a gradle build along with a `Plugin` class implementation and a manifest that points to this class. This is the entrypoint for the plugin where all metadata about the plugin is defined as well as all `Providers` offered by the plugin are registered.

=== Gradle project

Create a new project with a `build.gradle` file. We will use the shadowjar plugin to create our "fat jar"

.build.gradle
[source,groovy]
----
plugins {
    id "com.bertramlabs.asset-pipeline" version "3.3.2"
    id "com.github.johnrengelman.plugin-shadow" version "2.0.3"
}

apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'maven-publish'

group = 'com.example'
version = '1.0.0'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

ext.isReleaseVersion = !version.endsWith("SNAPSHOT")

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'com.morpheusdata:morpheus-plugin-api:0.9.0'
    compileOnly 'org.codehaus.groovy:groovy-all:2.5.6'

    /*
     When using custom libraries, use the gradle `implementation` directive
     instead of `compileOnly`.
     This will allow shadowJar to package the library into the resulting plugin and keep it
     isolated within the same classloader.
     */
}

tasks.assemble.dependsOn tasks.shadowJar
----

To let the Morpheus plugin manager know what class to load you must specify the class in jar's manifest:

.build.gradle
[source,groovy]
----
jar {
    manifest {
        attributes(
            'Plugin-Class': 'com.example.MyPlugin', //Reference to Plugin class
            'Plugin-Version': archiveVersion.get() // Get version defined in gradle
        )
    }
}
----

When writing plugin code, it is important to note a typical groovy/java project folder structure

.ls -R
[source,bash]
----
./
.gitignore
build.gradle
src/main/groovy/
src/main/resources/renderer/hbs/
src/test/groovy/
src/assets/images/
src/assets/javascript/
src/assets/stylesheets/
----

Be sure to configure your `.gitignore` file to ignore the `build/` directory which appears after performing your first build.

Most of the folder structure can be self-explanatory if familiar with groovy/java. Project packages live within `src/main/groovy` and contain source files ending in `.groovy`. View resources are stored in the `src/main/resources` subfolder and vary depending on the view renderer of choice. While static assets like icons or custom javascript live within the `src/assets` folder. This is handled by the http://www.asset-pipeline.com[Asset Pipeline] plugin. View rendering and static assets will be covered in more detail later.

Building a project is as simple as calling

[source,bash]
----
./gradlew shadowJar
----

**NOTE:** If the gradle wrapper does not yet exist, simply run `gradle wrapper` within the root of the project to generate the wrapper.

The resulting jar will exist, by default, in the `build/libs` directory of the project.




