== Getting Started

The structure of a Plugin is a typical "fat jar" (aka shadowJar). The plugin will include `morpheus-plugin-api` along with all the dependencies required to run. Though not required, it is often conventional to use the groovy programming language when developing plugins as can be seen in the samples. Morpheus is based on the groovy runtime and therefore allows full use of groovy 2.5.x.

The Structure of a project often starts with a gradle build along with a `Plugin` class implementation and a manifest that points to this class. This is the entrypoint for the plugin where all metadata about the plugin is defined as well as all `Providers` offered by the plugin are registered.

=== Gradle project

Create a new project with a `build.gradle` file. We will use the shadowjar plugin to create our "fat jar"

.build.gradle
[source,groovy]
----
apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'com.example'
version = '1.0.0'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

ext.isReleaseVersion = !version.endsWith("SNAPSHOT")

configurations {
    provided
}

dependencies {
    provided project(':morpheus-plugin-api')
}
----

To let the Morpheus plugin manager know what class to load you must specify the class in jar's manifest:

.build.gradle
[source,groovy]
----
jar {
	manifest {
		attributes(
				'Plugin-Class': 'com.example.MyPlugin',
				'Plugin-Version': archiveVersion.get() // Get version defined in gradle
		)
	}
}
----


