=== Release Notes

**Note:** The `morpheus-plugin-api` is still pre 1.0 and therefore core interfaces could change between releases. The minimum morpheus version needed to leverage some plugins starts with the 5.4.x series, however anything using plugin core 0.12.0 and above needs to use Morpheus 5.4.1 minimum. 6.0.x Morpheus versions use 0.14.x plugin-api and 6.2.x Morpheus versions use 0.15.x plugin-api. Efforts are being made to preserve some backwards compatibility as we get closer to 1.0 versions.

* **0.15.1**
** Moved most Providers new packages folder `com.morpheusdata.core.providers`
** Deprecated `OptionSourceProvider` in favor of new `DatasetProvider`
*** Enables scribe export/import object reference mapping and hcl data lookup as well
** Service Consistency work in the `MorpheusContext`.
*** Created new `MorpheusDataService` interface reference that allows for using dynamic db queries and object marshalling into the core/api models.
** New `StorageProvider` work began for abstracting various storage providers within morpheus.
** Enhanced `NetworkProvider` to support `Router` and `SecurityGroup` representations.
* ** 0.15.0**
** Filling in more Models and Cloud representations.
* ** 0.14.3**
** Filling in more Models and Cloud representations.
** Completed Localization support. Plugins now can be fully localized in both server side, and client side rendering. Guide provided as well.
* ** 0.14.2**
** Filling in more Models and Cloud representations.
** Added OptionType support for the `hidden` HTML Input.
* ** 0.14.1.**
** Filling in more Models and Cloud representations.
* ** 0.14.0**
** Filling in Cloud related gaps as we work to provide full cloud provider plugin support
** F5 Load Balancer support added and full abstractions for the `LoadBalancerProvider`.
* **0.13.4**
** Backup Plugin Support Added
** Cloud Plugin Coverage Improved
** DNS Plugins can now function standalone
** HTTP ApiClient now uses CharSequence for GString compatibility
** Improved Javadoc
** IPAMProvider Interface removed unnecessary methods
** Task Type Icons now use a getIcon() method on the Provider
** Network Pool Objects added IPv6 information (more to come)
** Context Services for Syncing additional cloud object types (such as Security Groups)
** Various other bug fixes and improvements on the road to 1.0.0
** Bump JVM Compatibility minimum to 1.11 (jdk 11)
* **0.13.1** - Added Credential Providers support as well as significant CloudProvider refactoring (more to follow)
* **0.12.5** - Task Providers now have a hasResults flag for result variable chaining.
* **0.12.4** - IPAM NetworkPoolType filters for handling multiple pool types in one integration. Deprecated reservePoolAddress from IPAMProvider as its no longer needed. Added typeCode to the `NetworkPoolIdentityProjection`. Added `{{nonce}}` helper to handlebars tab providers for injecting javascript safely within the Content Security Policies in place.
* **0.12.3** - Simplification and Polish if IPAM/DNS Interface Implementations (need Morpheus 5.4.4+). Added new ReportProvider helper for easier management of db connection use `withDbConnection { connection -> }`.
* **0.12.0** - Cloud Provider Plugin Critical Fixes (WIP). Added Plugin settings.
* **0.11.0** - Cloud Provider Plugin Support. UI Nonce token attribute added for injecting javascript securely and css. Network Provider Plugin support. Create providers for dynamically creating networks and network related objects.
* **0.10.0** - Custom Report Type Providers have been added.
* **0.8.0** - Overhauled DNS/IPAM Integrations, Reorganized contexts and standardized formats. Added utility classes for easier sync logic. Custom reports, Cloud Providers, Server Tabs, and more. Only compatible with Morpheus version `5.3.1` forward.

* **0.7.0** - Please note due to jcenter() EOL Don't use 0.7.0
* **0.6.0** - Primary Plugin target base version for 5.2.x Morpheus Releases

